name: "Deploy on Comment"

on:
  issue_comment:
    types: [created, edited]

jobs:
  test:
    name: Test on Comment
    if: contains(github.event.comment.body, '/test-web')
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Test
        run: |
          yarn test
        working-directory: ${{ github.workspace }}/web
