name: "Deploy on Comment"

on:
  issue_comment:
    types: [created, edited]

jobs:
  test:
    name: Test on Comment
    if: contains(github.event.comment.body, '/test-web')
    runs-on: ubuntu-latest

    steps:
      - name: Test
        run: |
          yarn test
      - name: Test Reporter with PR Comment
        uses: n-ryu/test-reporter@v0.0.2
